import { validateMindMap } from './mindmap';
import { validateHtmlDocument } from './html-document';
import { normalizeDetailLevel } from './detail';
import type { GenerationKind, ResultMeta, SavedResults } from './types';

export const CACHE_KEY = 'biliSum.results.v1';
interface Storage {
  get(key: string): Promise<Record<string, any>>;
  set(items: Record<string, unknown>): Promise<void>;
}
type Entry = { updatedAt: number; value: SavedResults };

function metadata(raw: any): ResultMeta {
  if (
    !raw ||
    ['model', 'source', 'createdAt'].some(
      (key) => typeof raw[key] !== 'string' || raw[key].length > 1000,
    )
  )
    throw new Error('Invalid cache metadata');
  return {
    model: raw.model,
    source: raw.source,
    createdAt: raw.createdAt,
    detailLevel: normalizeDetailLevel(raw.detailLevel),
  };
}
export function validateResults(raw: any): SavedResults | null {
  if (!raw || typeof raw.sourceHash !== 'string' || raw.sourceHash.length > 200)
    return null;
  const value: SavedResults = {
    sourceHash: raw.sourceHash,
    summary: null,
    map: null,
    html: null,
  };
  // A corrupt result should not prevent restoring the other format.
  try {
    if (
      raw.summary &&
      typeof raw.summary.markdown === 'string' &&
      raw.summary.markdown.length <= 180000 &&
      !raw.summary.incomplete
    )
      value.summary = {
        ...metadata(raw.summary),
        markdown: raw.summary.markdown,
      };
  } catch {
    /* Ignore invalid cached summaries. */
  }
  try {
    if (raw.map)
      value.map = { ...metadata(raw.map), tree: validateMindMap(raw.map.tree) };
  } catch {
    /* Ignore invalid cached maps. */
  }
  try {
    if (raw.html)
      value.html = {
        ...metadata(raw.html),
        document: validateHtmlDocument(raw.html.document),
      };
  } catch {
    /* Invalid HTML data must not block the summary or mind map. */
  }
  return value;
}

export function createResultCache(
  storage: Storage,
  lock?: (operation: () => Promise<void>) => Promise<void>,
) {
  let queue: Promise<void> = Promise.resolve();
  const read = async (): Promise<Record<string, Entry>> => {
    const raw = (await storage.get(CACHE_KEY))[CACHE_KEY];
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return {};
    const entries: [string, Entry][] = [];
    for (const [key, entry] of Object.entries(raw)) {
      if (!entry || typeof entry !== 'object') continue;
      const { updatedAt, value } = entry as Entry;
      const validated = validateResults(value);
      if (validated && Number.isFinite(updatedAt))
        entries.push([key, { updatedAt, value: validated }]);
    }
    return Object.fromEntries(entries);
  };
  return {
    async load(key: string) {
      return (await read())[key]?.value ?? null;
    },
    save(
      key: string,
      value: SavedResults,
      kind?: GenerationKind,
    ): Promise<void> {
      const operation = async () => {
        const cache = await read();
        const next = validateResults(value);
        if (!next) throw new Error('缓存内容无效。');
        const previous = cache[key]?.value;
        // Merge the format generated by this panel, preserving another panel's result.
        if (kind && previous?.sourceHash === next.sourceHash) {
          if (kind !== 'summary')
            next.summary = previous.summary ?? next.summary;
          if (kind !== 'map') next.map = previous.map ?? next.map;
          if (kind !== 'html') next.html = previous.html ?? next.html;
        }
        let entries = Object.entries(cache)
          .filter(([id]) => id !== key)
          .sort((a, b) => b[1].updatedAt - a[1].updatedAt);
        entries.unshift([key, { updatedAt: Date.now(), value: next }]);
        entries = entries.slice(0, 12);
        while (
          entries.length > 1 &&
          new TextEncoder().encode(JSON.stringify(Object.fromEntries(entries)))
            .length > 6_000_000
        )
          entries.pop();
        for (;;) {
          try {
            await storage.set({ [CACHE_KEY]: Object.fromEntries(entries) });
            return;
          } catch (error) {
            if (
              entries.length <= 1 ||
              !/quota|QUOTA_BYTES/i.test(
                error instanceof Error ? error.message : String(error),
              )
            )
              throw error;
            entries.pop();
          }
        }
      };
      const pending = queue
        .catch(() => {})
        .then(() => (lock ? lock(operation) : operation()));
      queue = pending;
      return pending;
    },
  };
}
